### ISSUE TITLE
pip install openqaoa throws some qiskit error

### ISSUE THREAD

**Issue by kidiki** [entropicalabs/openqaoa#296]
### When running in Colab, installing openqaoa with 'pip install openqaoa' and then simply running 'from openqaoa.problems import NumberPartition' throws and error 'ImportError: Missing optional 'qiskit' dependencies. To install run: pip install azure-quantum[qiskit]' 
However, after installing the error persists. 

### Screenshots
<img width="1119" alt="Screenshot 2023-12-04 at 23 17 46" src="https://github.com/entropicalabs/openqaoa/assets/22844056/bc4fd39e-8213-4d79-9ecf-572022552d90">

### Additional context
Current fix is installing openqaoa-core only.

**Comment by KilianPoirier** [comment]
This is addressed in PR#297

**Comment by bsiegelwax** [comment]
What's the status of this? I was just about to report this same issue.

**Comment by KilianPoirier** [comment]
Thanks for reporting that the issue still persists for you. This is due to a version limitation on `azure-quantum[qiskit]` ([more specifically](https://github.com/microsoft/azure-quantum-python/blob/main/azure-quantum/requirements-qiskit.txt)). When installing the `openqaoa` meta-package, the qiskit installation is apparently resolved by installing `openqaoa-qiskit` first and then `openqaoa-azure`, resulting in incompatibilities. This does not happen when installing locally.
This issue should be fixed on Azure Quantum's side.

In the meantime, here are some solutions you may want to try:

- installing the openqaoa meta-package can still be done by cloning the repository and using the makefile.
- installing through `pip` by choosing the plug-ins you may want to use (either -qiskit or -azure).
- modifying the qiskit to `0.43.3` on your current installation.

**Comment by gzquse** [comment]
Hi,

I am following the latest instructions.
The issue still persists. 

 ---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
File ~/conda/envs/myenv/lib/python3.10/site-packages/azure/quantum/qiskit/backends/backend.py:29
     [28](https://vscode-remote+ssh-002dremote-002bttu.vscode-resource.vscode-cdn.net/lustre/work/ziqguo/QML_2025/notebooks/~/conda/envs/myenv/lib/python3.10/site-packages/azure/quantum/qiskit/backends/backend.py:28) from qiskit.providers.models import BackendConfiguration
---> [29](https://vscode-remote+ssh-002dremote-002bttu.vscode-resource.vscode-cdn.net/lustre/work/ziqguo/QML_2025/notebooks/~/conda/envs/myenv/lib/python3.10/site-packages/azure/quantum/qiskit/backends/backend.py:29) from qiskit.qobj import Qobj, QasmQobj
     [30](https://vscode-remote+ssh-002dremote-002bttu.vscode-resource.vscode-cdn.net/lustre/work/ziqguo/QML_2025/notebooks/~/conda/envs/myenv/lib/python3.10/site-packages/azure/quantum/qiskit/backends/backend.py:30) from pyqir import Module

ImportError: cannot import name 'Qobj' from 'qiskit.qobj' (/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/qiskit/qobj/__init__.py)

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
Cell In[1], [line 2](vscode-notebook-cell:?execution_count=1&line=2)
      [1](vscode-notebook-cell:?execution_count=1&line=1) import networkx
----> [2](vscode-notebook-cell:?execution_count=1&line=2) from openqaoa.problems import MinimumVertexCover
      [4](vscode-notebook-cell:?execution_count=1&line=4) g = networkx.circulant_graph(6, [1])
      [5](vscode-notebook-cell:?execution_count=1&line=5) vc = MinimumVertexCover(g, field=1.0, penalty=10)

File ~/conda/envs/myenv/lib/python3.10/site-packages/openqaoa/__init__.py:1
----> [1](https://vscode-remote+ssh-002dremote-002bttu.vscode-resource.vscode-cdn.net/lustre/work/ziqguo/QML_2025/notebooks/~/conda/envs/myenv/lib/python3.10/site-packages/openqaoa/__init__.py:1) from .algorithms import QAOA, RQAOA, QAOABenchmark
      [2](https://vscode-remote+ssh-002dremote-002bttu.vscode-resource.vscode-cdn.net/lustre/work/ziqguo/QML_2025/notebooks/~/conda/envs/myenv/lib/python3.10/site-packages/openqaoa/__init__.py:2) from .problems import QUBO
      [3](https://vscode-remote+ssh-002dremote-002bttu.vscode-resource.vscode-cdn.net/lustre/work/ziqguo/QML_2025/notebooks/~/conda/envs/myenv/lib/python3.10/site-packages/openqaoa/__init__.py:3) from .backends import create_device

File ~/conda/envs/myenv/lib/python3.10/site-packages/openqaoa/algorithms/__init__.py:[1](https://vscode-remote+ssh-002dremote-002bttu.vscode-resource.vscode-cdn.net/lustre/work/ziqguo/QML_2025/notebooks/~/conda/envs/myenv/lib/python3.10/site-packages/openqaoa/algorithms/__init__.py:1)
----> 1 from .qaoa import QAOA, QAOAResult, QAOABenchmark
...
   (...)
     [46](https://vscode-remote+ssh-002dremote-002bttu.vscode-resource.vscode-cdn.net/lustre/work/ziqguo/QML_2025/notebooks/~/conda/envs/myenv/lib/python3.10/site-packages/azure/quantum/qiskit/backends/backend.py:46)         **fields
     [47](https://vscode-remote+ssh-002dremote-002bttu.vscode-resource.vscode-cdn.net/lustre/work/ziqguo/QML_2025/notebooks/~/conda/envs/myenv/lib/python3.10/site-packages/azure/quantum/qiskit/backends/backend.py:47)     ):

ImportError: Missing optional 'qiskit' dependencies. To install run: pip install azure-quantum[qiskit]

**Comment by KilianPoirier** [comment]
Hi @gzquse , thank you for pointing that out.

Have you tried branching out from `dev` instead of installing the package through `pip`? This is the quickest fix I can offer at the moment.

The `main` branch may be behind `dev` in terms of fixes, and since the test pipeline has been failing for other reasons, I'm not sure if the error persists. We will need to fix this before addressing the root problem with `qiskit` version.

**Comment by gzquse** [comment]
Hi @KilianPoirier ,

I followed the steps as dev required:
```
(myenv) login-20-26:/lustre/work/ziqguo/openqaoa$ git branch -a
* dev
  main
  remotes/origin/HEAD -> origin/main
  remotes/origin/dev
  remotes/origin/dev_fireopal
  remotes/origin/dev_fix_windows_workflow
  remotes/origin/dev_improve_notebooks
  remotes/origin/dev_mastereqn
  remotes/origin/dev_parallelization
  remotes/origin/dev_pyqir
  remotes/origin/dev_pyquil_parallelization
  remotes/origin/dev_qb
  remotes/origin/dev_test_pypi
  remotes/origin/dev_update_codecov
  remotes/origin/feat_pytket
(myenv) login-20-26:/lustre/work/ziqguo/openqaoa$ python --version
Python 3.10.16
(myenv) login-20-26:/lustre/work/ziqguo/openqaoa$ 

a(myenv) login-20-26:/lustre/work/ziqguo/openqaoa$ 
(myenv) login-20-26:/lustre/work/ziqguo/openqaoa$ python 
Python 3.10.16 (main, Dec 11 2024, 16:24:50) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> #some regular python libraries
>>> import networkx as nx
port matplotlib.pyplot as plt

#import problem classes from OQ for easy problem creation
from openqaoa.problems import MaximumCut, NumberPartition

#import the QAOA workflow model
from openqaoa import QAOA

#import method to specify the device
from openqaoa.backends import create_device>>> import numpy as np
>>> from pprint import pprint
>>> import matplotlib.pyplot as plt
>>> 
>>> #import problem classes from OQ for easy problem creation
>>> from openqaoa.problems import MaximumCut, NumberPartition
Traceback (most recent call last):
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/azure/quantum/qiskit/backends/backend.py", line 29, in <module>
    from qiskit.qobj import Qobj, QasmQobj
ImportError: cannot import name 'Qobj' from 'qiskit.qobj' (/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/qiskit/qobj/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/openqaoa/__init__.py", line 1, in <module>
    from .algorithms import QAOA, RQAOA, QAOABenchmark
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/openqaoa/algorithms/__init__.py", line 1, in <module>
    from .qaoa import QAOA, QAOAResult, QAOABenchmark
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/openqaoa/algorithms/qaoa/__init__.py", line 1, in <module>
    from .qaoa_workflow import QAOA
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/openqaoa/algorithms/qaoa/qaoa_workflow.py", line 5, in <module>
    from .qaoa_result import QAOAResult
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/openqaoa/algorithms/qaoa/qaoa_result.py", line 18, in <module>
    from ...backends.basebackend import QAOABaseBackend, QAOABaseBackendStatevector
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/openqaoa/backends/__init__.py", line 18, in <module>
    from .devices_core import DeviceLocal
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/openqaoa/backends/devices_core.py", line 5, in <module>
    from .plugin_finder import PLUGIN_DICT
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/openqaoa/backends/plugin_finder.py", line 58, in <module>
    PLUGIN_DICT = plugin_finder_dict()
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/openqaoa/backends/plugin_finder.py", line 21, in plugin_finder_dict
    output_dict[each_plugin_entry_point.name] = each_plugin_entry_point.load()
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/openqaoa_azure/backend_config.py", line 1, in <module>
    from .backends import DeviceAzure
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/openqaoa_azure/backends/__init__.py", line 1, in <module>
    from .devices import DeviceAzure
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/openqaoa_azure/backends/devices.py", line 3, in <module>
    from azure.quantum.qiskit import AzureQuantumProvider
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/azure/quantum/qiskit/__init__.py", line 8, in <module>
    from .provider import AzureQuantumProvider
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/azure/quantum/qiskit/provider.py", line 20, in <module>
    from azure.quantum.qiskit.backends.backend import AzureBackendBase
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/azure/quantum/qiskit/backends/__init__.py", line 6, in <module>
    from azure.quantum.qiskit.backends.ionq import (
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/azure/quantum/qiskit/backends/ionq.py", line 10, in <module>
    from .backend import AzureBackend, AzureQirBackend
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/azure/quantum/qiskit/backends/backend.py", line 34, in <module>
    raise ImportError(
ImportError: Missing optional 'qiskit' dependencies. To install run: pip install azure-quantum[qiskit]
>>> 
>>> #import the QAOA workflow model
>>> from openqaoa import QAOA
Traceback (most recent call last):
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/azure/quantum/qiskit/backends/backend.py", line 29, in <module>
    from qiskit.qobj import Qobj, QasmQobj
ImportError: cannot import name 'Qobj' from 'qiskit.qobj' (/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/qiskit/qobj/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/openqaoa/__init__.py", line 1, in <module>
    from .algorithms import QAOA, RQAOA, QAOABenchmark
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/openqaoa/algorithms/__init__.py", line 1, in <module>
    from .qaoa import QAOA, QAOAResult, QAOABenchmark
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/openqaoa/algorithms/qaoa/__init__.py", line 1, in <module>
    from .qaoa_workflow import QAOA
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/openqaoa/algorithms/qaoa/qaoa_workflow.py", line 6, in <module>
    from ..workflow_properties import CircuitProperties
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/openqaoa/algorithms/workflow_properties.py", line 7, in <module>
    from ..backends.devices_core import SUPPORTED_LOCAL_SIMULATORS
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/openqaoa/backends/__init__.py", line 18, in <module>
    from .devices_core import DeviceLocal
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/openqaoa/backends/devices_core.py", line 5, in <module>
    from .plugin_finder import PLUGIN_DICT
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/openqaoa/backends/plugin_finder.py", line 58, in <module>
    PLUGIN_DICT = plugin_finder_dict()
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/openqaoa/backends/plugin_finder.py", line 21, in plugin_finder_dict
    output_dict[each_plugin_entry_point.name] = each_plugin_entry_point.load()
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/openqaoa_azure/backend_config.py", line 1, in <module>
    from .backends import DeviceAzure
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/openqaoa_azure/backends/__init__.py", line 1, in <module>
    from .devices import DeviceAzure
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/openqaoa_azure/backends/devices.py", line 3, in <module>
    from azure.quantum.qiskit import AzureQuantumProvider
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/azure/quantum/qiskit/__init__.py", line 8, in <module>
    from .provider import AzureQuantumProvider
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/azure/quantum/qiskit/provider.py", line 20, in <module>
    from azure.quantum.qiskit.backends.backend import AzureBackendBase
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/azure/quantum/qiskit/backends/__init__.py", line 6, in <module>
    from azure.quantum.qiskit.backends.ionq import (
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/azure/quantum/qiskit/backends/ionq.py", line 10, in <module>
    from .backend import AzureBackend, AzureQirBackend
  File "/home/ziqguo/conda/envs/myenv/lib/python3.10/site-packages/azure/quantum/qiskit/backends/backend.py", line 34, in <module>
    raise ImportError(
ImportError: Missing optional 'qiskit' dependencies. To install run: pip install azure-quantum[qiskit]
>>> 
>>> #import method to specify the device

Dev install 

make dev-install

Successfully installed openqaoa-0.2.6

    raise ImportError(
ImportError: Missing optional 'qiskit' dependencies. To install run: pip install azure-quantum[qiskit]


```

It is the same error. Please let me know if I made some mistakes.
Meanwhile, would you mind to provide me a step-by-step guides for running the first workflow.

**Comment by gzquse** [comment]
Additional information:

Problem solved using a brand new conda env:)
